// common.js V3 FINAL - FIXED Single Source of Truth
const CM_R2_API = window.CM_R2_API || "https://r2-proxy.vasan-jitpim.workers.dev";
window.CM_R2_API = CM_R2_API;
const CM_D1_API = window.CM_D1_API || (CM_R2_API + "/api");
window.CM_D1_API = CM_D1_API;
const CM_ADMIN_EMAIL = "vasan.jitpim@gmail.com";
const CM_ADMIN_NO = "CM-0000";
window.CM_ADMIN_EMAIL = CM_ADMIN_EMAIL;
window.CM_ADMIN_NO = CM_ADMIN_NO;
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
window.escapeHtml=escapeHtml;
function showModal(msg,title){title=title||"แจ้งเตือน";const m=document.getElementById("cmModal");if(!m){alert(msg);return;}const t=m.querySelector("#cmModalTitle");const b=m.querySelector("#cmModalBody");if(t)t.textContent=title;if(b)b.textContent=msg;m.classList.remove("hidden");m.classList.add("flex");}
window.showModal=showModal;
function showModalConfirm(msg,title,onOk){if(typeof title==="function"){onOk=title;title="ยืนยัน";}title=title||"ยืนยัน";const m=document.getElementById("cmModalConfirm");if(!m){if(confirm(msg)&&onOk)onOk();return;}const t=m.querySelector("#cmConfirmTitle");const b=m.querySelector("#cmConfirmBody");const ok=m.querySelector("#cmConfirmOk");const cancel=m.querySelector("#cmConfirmCancel");if(t)t.textContent=title;if(b)b.textContent=msg;m.classList.remove("hidden");m.classList.add("flex");if(ok){ok.onclick=()=>{m.classList.add("hidden");m.classList.remove("flex");if(onOk)onOk();};}if(cancel){cancel.onclick=()=>{m.classList.add("hidden");m.classList.remove("flex");};}}
window.showModalConfirm=showModalConfirm;
let _supaInstance=window.supa||null;
function getSupa(){if(_supaInstance)return _supaInstance;if(window.supabase){try{_supaInstance=window.supabase.createClient("https://mgandefbbgvlfqqzfnoe.supabase.co","sb_publishable_36w7j8f8s0k3l2m1n0p9q8r7s6t5u4v");window.supa=_supaInstance;return _supaInstance;}catch(e){console.error("Supabase init fail",e);return null;}}return null;}
window.getSupa=getSupa;window.supa=window.supa||getSupa();
function cmIsAdmin(email,memberNo){if(!email)return false;const e=String(email).toLowerCase().trim();return e===CM_ADMIN_EMAIL.toLowerCase();}
window.cmIsAdmin=cmIsAdmin;
async function cmFetchD1(path){try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);const res=await fetch(CM_D1_API+path,{signal:controller.signal});clearTimeout(timeout);if(!res.ok)throw new Error("D1 status "+res.status);return await res.json();}catch(err){console.error("cmFetchD1 fail",path,err);return null;}}
window.cmFetchD1=cmFetchD1;
async function cmUploadR2(formData){try{const res=await fetch(CM_R2_API+"/upload",{method:"POST",body:formData});if(!res.ok)throw new Error("R2 upload fail "+res.status);return await res.json();}catch(err){console.error("cmUploadR2 fail",err);throw err;}}
window.cmUploadR2=cmUploadR2;
(function(){window.toggleMobileNav=function(){const nav=document.getElementById('mobileNav');const overlay=document.getElementById('mobileOverlay');if(!nav)return;const isOpen=nav.classList.contains('translate-x-0');if(isOpen){nav.classList.remove('translate-x-0');nav.classList.add('-translate-x-full');if(overlay)overlay.classList.add('hidden');document.body.style.overflow='';}else{nav.classList.remove('-translate-x-full');nav.classList.add('translate-x-0');if(overlay)overlay.classList.remove('hidden');document.body.style.overflow='hidden';}};window.closeMobileNav=function(){const nav=document.getElementById('mobileNav');const overlay=document.getElementById('mobileOverlay');if(nav){nav.classList.remove('translate-x-0');nav.classList.add('-translate-x-full');}if(overlay)overlay.classList.add('hidden');document.body.style.overflow='';};window.showToast=function(msg,type='success'){let container=document.getElementById('toastContainer');if(!container){container=document.createElement('div');container.id='toastContainer';container.className='fixed bottom-4 right-4 z-[9999] flex flex-col gap-2';document.body.appendChild(container);}const toast=document.createElement('div');const bg=type==='error'?'bg-red-600':type==='warn'?'bg-yellow-600':'bg-zinc-900';toast.className=`${bg} text-white px-4 py-3 rounded-xl shadow-lg text-sm font-medium max-w-sm border border-white/10`;toast.textContent=msg;container.appendChild(toast);setTimeout(()=>{toast.style.opacity='0';toast.style.transform='translateX(100%)';toast.style.transition='all 0.3s';setTimeout(()=>toast.remove(),300);},2500);};window.copyToClipboard=async function(text){try{await navigator.clipboard.writeText(text);window.showToast('คัดลอกแล้ว ✓');return true;}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();window.showToast('คัดลอกแล้ว ✓');return true;}};window.closeAllMenus=function(){document.querySelectorAll('[data-dropdown]').forEach(el=>el.classList.add('hidden'));};document.addEventListener('click',(e)=>{const nav=document.getElementById('mobileNav');const btn=document.querySelector('[data-mobile-toggle]');if(nav&&!nav.contains(e.target)&&btn&&!btn.contains(e.target)){if(nav.classList.contains('translate-x-0')){window.closeMobileNav();}}if(!e.target.closest('[data-dropdown-trigger]')&&!e.target.closest('[data-dropdown]')){window.closeAllMenus();}});window.addEventListener('resize',()=>{if(window.innerWidth>=1024){window.closeMobileNav();}});console.log('✅ common.js V3 FINAL loaded - Singleton + FIXED all daily bugs');})();
